### PR TITLE
Added dashboard-metrics-scraper support to chart

### PR DESCRIPTION
**Pull request by davidalger**
This amends work done on kubernetes/dashboard#4502 to include the deployment of the recommended sidecar container which is required by the dashboard UI to display metrics gathered from metrics-server. With heapster being deprecated, and this a part of the recommended deployment, it would make sense to me that this is included in the kubernetes-dashboard chart vs being split off to a seperate chart.

I've got this deployed into a test EKS cluster which also has metrics-server deployed:
```
helm install metrics-server -n kube-system stable/metrics-server
```

Note however that in some cases `metrics-server` may already be deployed by default. Per [Kubernetes documentation](https://kubernetes.io/docs/tasks/debug-application-cluster/resource-metrics-pipeline/) `metrics-server` is for example deployed by default in clusters created by `kube-up.sh` script.

The graphs began displaying shortly after updating the deployed chart into my cluster:
Screen-Shot-2020-01-02-14-50-40 47-16e5vTQriSEmBVQLlTIWmIKO4UPLrK9GKt2lzcqxmVrg19oXrj5A0J9AKppbZKwByQcoiB8CsV55uvZhpF28uBkTxA9vKe8cxuyB

I needed this functionality to transition my own deployment of the kubernetes-dashboard from using raw manifests for v2 beta to using a chart version of the dashboard. Would love to see it included in the official chart when published though, so am taking the time to share my work here with the hope it can be used to amend the PR currently in progress at kubernetes/dashboard#4502

### CODE REVIEW

**Comment by bskim45** [comment]
Awesome. Quick question: Have you ever tried different name of the scraper other than `metrics-scraper`? It seems like the name of the scraper used in dashboard v2 is hardcoded and it's unable to change the target scraper service unless the service endpoint is specified.

**Comment by davidalger** [comment]
@bskim45 I haven't tried with a different name. Never deployed this with heapster, but looks like the same was true there and the integrations documentation actually indicated it must be deployed with a specific name. I'd assume for the time being that metrics-scraper must be named as "metrics-scraper" to function unless someone tries and says otherwise.

The example files (and what's currently in this chart) also hard code the heapster and dashboard-metrics-scraper names…
https://github.com/kubernetes/dashboard/blob/master/aio/deploy/recommended/05_dashboard-rbac.yaml#L34-L41

**Comment by bskim45** [comment]
True. Looks good to me!

**Comment by davidalger** [comment]
Closing as the two commits on this have been picked onto the original PR. Thanks @desaintmartin!

**Pull request closed without merging**
